### ISSUE TITLE
English translation

### ISSUE THREAD

**Issue by dakkusingh** [AlexanderLill/PP-Crypto-Parser#2]
Hi,
Firstly thanks for creating this parser. Is it possible to make the exported files work for english language??

**Comment by AlexanderLill** [comment]
Dear @dakkusingh, thanks for your comment! I can try to add a parameter to the script to switch between english and german. I am not sure when I will get to it, but you could help me by providing me the names of the columns you would need. You can get them, for example by exporting your current data to CSV, and sending me the first line of that file, so I know which words to use for the english version :)

**Comment by Petemir** [comment]
German:
```
DEPOT_CSV_HEADER = "Datum,Uhrzeit,Typ,Wertpapier,Stück,Kurs,Betrag,Gebühren,Steuern,Gesamtpreis,Konto,Gegenkonto,Notiz,Quelle"

ACCOUNT_CSV_HEADER = "Datum,Uhrzeit,Typ,Betrag,Saldo,Wertpapier,Stück,pro Aktie,Gegenkonto,Notiz,Quelle"
```

English:
```
DEPOT_CSV_HEADER = "Date,Time,Type,Security Name,Shares,Exchange Rate,Gross Amount,Fees,Taxes,Value,Securities Account,Offset Account,Note,Quelle"

ACCOUNT_CSV_HEADER = "Date,Time,Type,Value,Saldo,Security Name,Shares,pro Aktie,Offset Account,Note,Quelle"
```

I couldn't translate `Saldo, pro Aktie, Quelle`, as I don't know to what PP columns they match (they weren't shown in the examples). 

Columns can be found [here (EN)](https://github.com/portfolio-performance/portfolio/blob/master/name.abuchen.portfolio/src/name/abuchen/portfolio/messages.properties) and [here (DE)](https://github.com/portfolio-performance/portfolio/blob/master/name.abuchen.portfolio/src/name/abuchen/portfolio/messages_de.properties), at `CSVColumn_...` . 

Transaction types are [here (EN)](https://github.com/portfolio-performance/portfolio/blob/12fcd907fee083d8ae4fc9d1b3dab5069c94b6eb/name.abuchen.portfolio/src/name/abuchen/portfolio/model/labels.properties) and [here (DE)](https://github.com/portfolio-performance/portfolio/blob/12fcd907fee083d8ae4fc9d1b3dab5069c94b6eb/name.abuchen.portfolio/src/name/abuchen/portfolio/model/labels_de.properties), at the top.

**Comment by AlexanderLill** [comment]
Hey @dakkusingh, you can now use the parameter `-l en` to export English CSVs :)
