### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by Frugipon** [AlexanderLill/PP-Crypto-Parser#3]
Hello and thank you very much for the parser.

Can I request that you also add French translation as in #2  ?

**Comment by AlexanderLill** [comment]
Hey @Frugipon, I can try but can't make any promises regarding when I will get to it. Feel free to create a pull request, the necessary translations should all be available within the original portfolio-performance repository, and the amount of changes to the code should be minimal :)

**Comment by AlexanderLill** [comment]
I just committed some documentation that I started two weeks ago that might be helpful: https://github.com/AlexanderLill/PP-Crypto-Parser/blob/master/src/i18n/i18n.md

**Comment by AlexanderLill** [comment]
Done, with commit [1f51013](https://github.com/AlexanderLill/PP-Crypto-Parser/commit/1f510134c833ddeabe3b9708564e3a5b1905c14b) this should now work :)
