### ISSUE TITLE
staking of ETH and BTC

### ISSUE THREAD

**Issue by christen90** [AlexanderLill/PP-Crypto-Parser#4]
Hello Alexander,
also thanks from my side for implementing that parser.

Somehow I'm not able to process my transactions. Can you please have a look and give a hint why it is not working?
I'm running it under python 3.12 (PyCharm on Windows) `cly.py -fc "EUR" -o "./output" -v ".\input\Alle_historischen_Kurse.csv" ".\input\ledgers.csv" -cm "{\"BTC-EUR\": \"XXBTZEUR\", \"ETH-EUR\": \"XETHZEUR\"}"`

_Alle_historischen_Kurse.csv_ looks like this
> Datum;XETHZEUR;XXBTZEUR
> 2000-01-03;;

Kraken is in use for historic rates

_ledgers.csv_ looks like this
> "txid","refid","time","type","subtype","aclass","asset","amount","fee","balance"
> "LVOEPI-YP2LX-H2RBFQ","ST5ENW3-ITDUB-JOLAPV","2024-03-11 12:01:02","staking","","currency","BTC.M",0.0000007100,0,0.0100000000
> "L5LDYP-Y2KAB-CYRTJV","Unknown","2024-03-11 16:31:11","earn","","currency","BTC.M",-0.0100000000,0,0.0000000000
> "LBAOX7-N4RCV-V7LXMB","Unknown","2024-03-11 16:31:11","earn","","currency","BTC",0.0100000000,0,0.0100000000
> "LXCWAU-5PRVS-LJJ2XU","Unknown","2024-03-12 09:29:47","earn","","currency","BTC",0.0000000841,0,0.0123456789
> "LVG4ZQ-UQXEX-6PSBDO","FTBYaWb-BfahyMc2OmXHb8w2yL1awG","2024-02-17 21:27:53","transfer","stakingfromspot","currency","BTC.M",0.2000000000,0,0.2000000000
> "LA7CPK-J4OIC-BRX5BR","FTNma83-iN8rBS0YNwDnYrPM26sDiR","2023-11-06 03:42:46","transfer","spottostaking","currency","ETH",-0.035450332600,0,0.0000000000
> "L6ZYVO-LBPXG-RNLACS","FTQLer0-sFkLOKVSujzJsgBa2euclW","2024-02-17 21:27:01","transfer","spottostaking","currency","BTC",-0.2000000000,0,0.0000000000
> "LQRDFV-IMJWR-SNOJU4","FTOapcj-YbDWR2avhCgM24gQJ3r3G8","2024-02-21 03:46:05","transfer","stakingfromspot","currency","ETH2.S",0.0003238736,0,0.0357742062
> "LOXJYV-R2WCQ-JDUJSK","QCCC3OQ-AYISNK-MX22N6","2021-04-20 15:26:01","deposit","","currency","EUR",1000.0000,0,1000.0000

No staking rewards gets exported.
For the refid Unknown i get Can't process case: earn info: dup
For the rest Can't process case: transfer info: nondup
Can't process case: deposit info: nondup
Can't process case: staking info: nondup

BR Christian

**Comment by AlexanderLill** [comment]
Dear @christen90, thank you for your message and issue report! I have downloaded an export from kraken and have also found this new, not yet in my parser implemented "earn" transactions with "Unknown" refid.

I will check how to properly implement these, but it might be May until there is a fix - feel free to create a PR if you want to try yourself :)

**Comment by AlexanderLill** [comment]
Dear @christen90, I have improved the transaction processing, so many of your "Can't process case" messages should disappear now. For the cases with the `Unknown` `refid`, I have checked my export and also found these - on the Kraken website, these transaction do have a `refid`, so I contacted Kraken support and will keep you updated here.

Have fun trying the new version!

**Comment by AlexanderLill** [comment]
The bug with the unknown refid was confirmed, and there will be a fix (although there is no timeline for it yet):
> Thank you for reaching out to us regarding the issues you are having with the RefID.
>
> As you have aptly pointed out, the RefID is present in Kraken PRO but is sometimes missing in the Export CSV file for some Earn transactions.
>  
> We have notified our developers and they will be rolling out a fix to ensure this functions as intended. Unfortunately we do not have an exact timeline of when this will happen.
>  
> Again, we thank you for your observation and feedback.

**Comment by AlexanderLill** [comment]
It seems that there are no more `Unknown` `refid`s in current exports. So I am closing this, let me know if there are any other issues!
